services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
    restart: always

  backend:
    build:
      context: ./backend
    image: d1zero/kittygram_backend:latest
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - kittygram_network
    restart: always

  frontend:
    build:
      context: ./frontend
    image: d1zero/kittygram_frontend:latest
    volumes:
      - static:/app/static
    depends_on:
      - backend
    networks:
      - kittygram_network
    restart: always

  gateway:
    build:
      context: ./nginx
    image: d1zero/kittygram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network
    restart: always

volumes:
  static:
  media:
  pg_data:

networks:
  kittygram_network:
    driver: bridge