services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network
    healthcheck:
      test: ["CMD-SHELL","pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kittygram_network

  frontend:
    build:
      context: ./frontend
    volumes:
      - static:/app/static
    depends_on:
      - backend
    networks:
      - kittygram_network

  gateway:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network

volumes:
  static:
  media:
  pg_data:

networks:
  kittygram_network:
    driver: bridge