#cloud-config

package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - apt-get install -y docker.io docker-compose
  - systemctl enable docker
  - systemctl start docker
  - sudo groupadd docker
  - sudo usermod -aG docker $USER
  - newgrp docker